### ISSUE TITLE
Unity FTM Bangla update for World Bank study

### ISSUE THREAD

**Issue by burrage** [curiouslearning/FeedTheMonster#34]
Waiting for Stephanie to finalize scope and sequence.

New Assets will be here: https://trello.com/c/2CQsfnL8/3-bangla

**Comment by burrage** [comment]
@weepingwitch New Bangla assets added! Should be ready to rock!

**Comment by weepingwitch** [comment]
https://drive.google.com/file/d/1q096Pdcyvn3raI_8h2ixYcu2csdFqW7o/view?usp=drive_link

**Comment by burrage** [comment]
@weepingwitch From the QA in late October, it looks like we would need to rebuild this from the levelgen which has already been done.

**Comment by burrage** [comment]
Going to close this and spin up the QA items we found as a separate task.
